/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

/*#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)*/

GtkWidget*
create_Modificar_cliente (void)
{
  GtkWidget *Modificar_cliente;
  GdkPixbuf *Modificar_cliente_icon_pixbuf;
  GtkWidget *table14;
  GtkWidget *label118;
  GtkWidget *entry_modificarclientebuscar;
  GtkWidget *btn_modificarcliente;
  GtkWidget *image52;
  GtkWidget *label96;
  GtkWidget *label98;
  GtkWidget *label100;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *label104;
  GtkWidget *label105;
  GtkWidget *label106;
  GtkWidget *label107;
  GtkWidget *label125;
  GtkWidget *label126;
  GtkWidget *label159;
  GtkWidget *entry_modificarclientenombre;
  GtkWidget *entry_modificarclientedomicilio;
  GtkWidget *entry_modificarclientecolonia;
  GtkWidget *entry_modificarclienteciudad_estado;
  GtkWidget *entry_modificarclientetelefono2;
  GtkWidget *entry_modificarclientetelefono3;
  GtkWidget *entry_modificarclienteentre_calles;
  GtkWidget *entry_modificarclientecontacto;
  GtkWidget *entry_modificarclientevencimiento;
  GtkWidget *entry_modificarclientetelefono;
  GtkWidget *label97;
  GtkWidget *scrolledwindow9;
  GtkWidget *clist_modificarcliente;
  GtkWidget *label93;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkWidget *label99;
  GtkWidget *image50;
  GtkWidget *btn_modificarclientecancelar;
  GtkWidget *image53;
  GtkWidget *combo_modificarclientelista;
  GtkWidget *combo_entry_modificarclientelista;
  GtkWidget *combo_modificarclientepago;
  GList *combo_modificarclientepago_items = NULL;
  GtkWidget *combo_entry_modificarclientepago;
  GtkWidget *combo_modificarclienteformato;
  GList *combo_modificarclienteformato_items = NULL;
  GtkWidget *combo_entry_modificarclienteformato;
  GtkWidget *entry_modificarclientecp;
  GtkWidget *entry_modificarclienterfc;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  Modificar_cliente = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Modificar_cliente, 700, 418);
  gtk_container_set_border_width (GTK_CONTAINER (Modificar_cliente), 2);
  gtk_window_set_title (GTK_WINDOW (Modificar_cliente), _("Modificar Datos de Clientes"));
  gtk_window_set_position (GTK_WINDOW (Modificar_cliente), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (Modificar_cliente), FALSE);
  Modificar_cliente_icon_pixbuf = create_pixbuf ("icono_carnesbecerra.png");
  if (Modificar_cliente_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (Modificar_cliente), Modificar_cliente_icon_pixbuf);
      gdk_pixbuf_unref (Modificar_cliente_icon_pixbuf);
    }

  table14 = gtk_table_new (18, 9, FALSE);
  gtk_widget_show (table14);
  gtk_container_add (GTK_CONTAINER (Modificar_cliente), table14);
  gtk_container_set_border_width (GTK_CONTAINER (table14), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table14), 2);

  label118 = gtk_label_new_with_mnemonic (_("_Buscar "));
  gtk_widget_show (label118);
  gtk_table_attach (GTK_TABLE (table14), label118, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label118, 5, 17);
  gtk_label_set_justify (GTK_LABEL (label118), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label118), 0.9, 0.5);

  entry_modificarclientebuscar = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientebuscar);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientebuscar, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientebuscar, 37, 25);

  btn_modificarcliente = gtk_button_new ();
  gtk_widget_show (btn_modificarcliente);
  gtk_table_attach (GTK_TABLE (table14), btn_modificarcliente, 0, 4, 17, 18,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (btn_modificarcliente, 103, 35);
  gtk_widget_add_accelerator (btn_modificarcliente, "clicked", accel_group,
                              GDK_F1, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (btn_modificarcliente), GTK_RELIEF_NONE);

  image52 = create_pixmap (Modificar_cliente, "carnesbecerra_aceptar.png");
  gtk_widget_show (image52);
  gtk_container_add (GTK_CONTAINER (btn_modificarcliente), image52);

  label96 = gtk_label_new_with_mnemonic (_("_Nombre "));
  gtk_widget_show (label96);
  gtk_table_attach (GTK_TABLE (table14), label96, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label96), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label96), 0, 0.5);

  label98 = gtk_label_new_with_mnemonic (_("C_olonia "));
  gtk_widget_show (label98);
  gtk_table_attach (GTK_TABLE (table14), label98, 4, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label98), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label98), 0, 0.5);

  label100 = gtk_label_new_with_mnemonic (_("C._P."));
  gtk_widget_show (label100);
  gtk_table_attach (GTK_TABLE (table14), label100, 4, 5, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label100), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label100), 0, 0.5);

  label101 = gtk_label_new_with_mnemonic (_("_Telefono "));
  gtk_widget_show (label101);
  gtk_table_attach (GTK_TABLE (table14), label101, 4, 5, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label101), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label101), 0, 0.5);

  label102 = gtk_label_new (_("Telefono 2"));
  gtk_widget_show (label102);
  gtk_table_attach (GTK_TABLE (table14), label102, 4, 5, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label102), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label102), 0, 0.5);

  label103 = gtk_label_new (_("Telefono 3"));
  gtk_widget_show (label103);
  gtk_table_attach (GTK_TABLE (table14), label103, 4, 5, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label103), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label103), 0, 0.5);

  label104 = gtk_label_new_with_mnemonic (_("_RFC"));
  gtk_widget_show (label104);
  gtk_table_attach (GTK_TABLE (table14), label104, 4, 5, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label104), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label104), 0, 0.5);

  label105 = gtk_label_new_with_mnemonic (_("R_eferencia "));
  gtk_widget_show (label105);
  gtk_table_attach (GTK_TABLE (table14), label105, 4, 5, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label105, 60, 17);
  gtk_label_set_justify (GTK_LABEL (label105), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label105), 0, 0.5);

  label106 = gtk_label_new_with_mnemonic (_("_Contacto "));
  gtk_widget_show (label106);
  gtk_table_attach (GTK_TABLE (table14), label106, 4, 5, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label106, 56, 17);
  gtk_label_set_justify (GTK_LABEL (label106), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label106), 0, 0.5);

  label107 = gtk_label_new_with_mnemonic (_("_Lista de precios "));
  gtk_widget_show (label107);
  gtk_table_attach (GTK_TABLE (table14), label107, 4, 5, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label107, 60, 17);
  gtk_label_set_justify (GTK_LABEL (label107), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label107), 0, 0.5);

  label125 = gtk_label_new_with_mnemonic (_("P_ago "));
  gtk_widget_show (label125);
  gtk_table_attach (GTK_TABLE (table14), label125, 4, 5, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label125, 34, 17);
  gtk_label_set_justify (GTK_LABEL (label125), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label125), 0, 0.5);

  label126 = gtk_label_new_with_mnemonic (_("_Formato "));
  gtk_widget_show (label126);
  gtk_table_attach (GTK_TABLE (table14), label126, 4, 5, 15, 16,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label126, 52, 17);
  gtk_label_set_justify (GTK_LABEL (label126), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label126), 0, 0.5);

  label159 = gtk_label_new_with_mnemonic (_("_Vencimiento (d\303\255as) "));
  gtk_widget_show (label159);
  gtk_table_attach (GTK_TABLE (table14), label159, 4, 5, 16, 17,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label159, 120, 17);
  gtk_label_set_justify (GTK_LABEL (label159), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label159), 0, 0.5);

  entry_modificarclientenombre = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientenombre);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientenombre, 5, 9, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientenombre, 165, 25);

  entry_modificarclientedomicilio = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientedomicilio);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientedomicilio, 5, 9, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientedomicilio, 165, 25);

  entry_modificarclientecolonia = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientecolonia);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientecolonia, 5, 8, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientecolonia, 80, 25);

  entry_modificarclienteciudad_estado = gtk_entry_new ();
  gtk_widget_show (entry_modificarclienteciudad_estado);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclienteciudad_estado, 5, 8, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclienteciudad_estado, 80, 25);

  entry_modificarclientetelefono2 = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientetelefono2);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientetelefono2, 5, 7, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientetelefono2, 20, 25);

  entry_modificarclientetelefono3 = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientetelefono3);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientetelefono3, 5, 7, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientetelefono3, 20, 25);

  entry_modificarclienteentre_calles = gtk_entry_new ();
  gtk_widget_show (entry_modificarclienteentre_calles);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclienteentre_calles, 5, 9, 11, 12,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclienteentre_calles, 70, 25);

  entry_modificarclientecontacto = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientecontacto);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientecontacto, 5, 8, 12, 13,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientecontacto, 80, 25);

  entry_modificarclientevencimiento = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientevencimiento);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientevencimiento, 5, 6, 16, 17,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientevencimiento, 1, 25);
  gtk_entry_set_text (GTK_ENTRY (entry_modificarclientevencimiento), _("0"));

  entry_modificarclientetelefono = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientetelefono);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientetelefono, 5, 7, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientetelefono, 20, 25);

  label97 = gtk_label_new_with_mnemonic (_("_Domicilio "));
  gtk_widget_show (label97);
  gtk_table_attach (GTK_TABLE (table14), label97, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label97), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label97), 0, 0.5);

  scrolledwindow9 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow9);
  gtk_table_attach (GTK_TABLE (table14), scrolledwindow9, 0, 3, 3, 17,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (scrolledwindow9, 360, 340);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow9), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  clist_modificarcliente = gtk_clist_new (3);
  gtk_widget_show (clist_modificarcliente);
  gtk_container_add (GTK_CONTAINER (scrolledwindow9), clist_modificarcliente);
  gtk_clist_set_column_width (GTK_CLIST (clist_modificarcliente), 0, 40);
  gtk_clist_set_column_width (GTK_CLIST (clist_modificarcliente), 1, 214);
  gtk_clist_set_column_width (GTK_CLIST (clist_modificarcliente), 2, 39);
  gtk_clist_column_titles_show (GTK_CLIST (clist_modificarcliente));

  label93 = gtk_label_new (_("C"));
  gtk_widget_show (label93);
  gtk_clist_set_column_widget (GTK_CLIST (clist_modificarcliente), 0, label93);
  gtk_label_set_justify (GTK_LABEL (label93), GTK_JUSTIFY_LEFT);

  label94 = gtk_label_new (_("Nombre"));
  gtk_widget_show (label94);
  gtk_clist_set_column_widget (GTK_CLIST (clist_modificarcliente), 1, label94);
  gtk_label_set_justify (GTK_LABEL (label94), GTK_JUSTIFY_LEFT);

  label95 = gtk_label_new (_("Lista"));
  gtk_widget_show (label95);
  gtk_clist_set_column_widget (GTK_CLIST (clist_modificarcliente), 2, label95);
  gtk_label_set_justify (GTK_LABEL (label95), GTK_JUSTIFY_LEFT);

  label99 = gtk_label_new_with_mnemonic (_("C_iudad y Estado "));
  gtk_widget_show (label99);
  gtk_table_attach (GTK_TABLE (table14), label99, 4, 5, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (label99, 103, 17);
  gtk_label_set_justify (GTK_LABEL (label99), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label99), 0, 0.5);

  image50 = create_pixmap (Modificar_cliente, NULL);
  gtk_widget_show (image50);
  gtk_table_attach (GTK_TABLE (table14), image50, 0, 9, 0, 18,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (image50), 0, 0);

  btn_modificarclientecancelar = gtk_button_new ();
  gtk_widget_show (btn_modificarclientecancelar);
  gtk_table_attach (GTK_TABLE (table14), btn_modificarclientecancelar, 4, 9, 17, 18,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (btn_modificarclientecancelar, 103, 35);
  gtk_widget_add_accelerator (btn_modificarclientecancelar, "clicked", accel_group,
                              GDK_F5, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_widget_add_accelerator (btn_modificarclientecancelar, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (btn_modificarclientecancelar), GTK_RELIEF_NONE);

  image53 = create_pixmap (Modificar_cliente, "carnesbecerra_cancelar.png");
  gtk_widget_show (image53);
  gtk_container_add (GTK_CONTAINER (btn_modificarclientecancelar), image53);

  combo_modificarclientelista = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_modificarclientelista)->popwin),
                     "GladeParentKey", combo_modificarclientelista);
  gtk_widget_show (combo_modificarclientelista);
  gtk_table_attach (GTK_TABLE (table14), combo_modificarclientelista, 5, 7, 13, 14,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (combo_modificarclientelista, 20, 25);

  combo_entry_modificarclientelista = GTK_COMBO (combo_modificarclientelista)->entry;
  gtk_widget_show (combo_entry_modificarclientelista);
  gtk_editable_set_editable (GTK_EDITABLE (combo_entry_modificarclientelista), FALSE);

  combo_modificarclientepago = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_modificarclientepago)->popwin),
                     "GladeParentKey", combo_modificarclientepago);
  gtk_widget_show (combo_modificarclientepago);
  gtk_table_attach (GTK_TABLE (table14), combo_modificarclientepago, 5, 7, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (combo_modificarclientepago, 20, 25);
  combo_modificarclientepago_items = g_list_append (combo_modificarclientepago_items, (gpointer) _("Contado"));
  combo_modificarclientepago_items = g_list_append (combo_modificarclientepago_items, (gpointer) _("Credito"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_modificarclientepago), combo_modificarclientepago_items);
  g_list_free (combo_modificarclientepago_items);

  combo_entry_modificarclientepago = GTK_COMBO (combo_modificarclientepago)->entry;
  gtk_widget_show (combo_entry_modificarclientepago);
  gtk_editable_set_editable (GTK_EDITABLE (combo_entry_modificarclientepago), FALSE);

  combo_modificarclienteformato = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo_modificarclienteformato)->popwin),
                     "GladeParentKey", combo_modificarclienteformato);
  gtk_widget_show (combo_modificarclienteformato);
  gtk_table_attach (GTK_TABLE (table14), combo_modificarclienteformato, 5, 7, 15, 16,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (combo_modificarclienteformato, 20, 25);
  combo_modificarclienteformato_items = g_list_append (combo_modificarclienteformato_items, (gpointer) _("Ticket"));
  combo_modificarclienteformato_items = g_list_append (combo_modificarclienteformato_items, (gpointer) _("Factura"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo_modificarclienteformato), combo_modificarclienteformato_items);
  g_list_free (combo_modificarclienteformato_items);

  combo_entry_modificarclienteformato = GTK_COMBO (combo_modificarclienteformato)->entry;
  gtk_widget_show (combo_entry_modificarclienteformato);
  gtk_editable_set_editable (GTK_EDITABLE (combo_entry_modificarclienteformato), FALSE);

  entry_modificarclientecp = gtk_entry_new ();
  gtk_widget_show (entry_modificarclientecp);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclientecp, 5, 6, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclientecp, 1, 25);

  entry_modificarclienterfc = gtk_entry_new ();
  gtk_widget_show (entry_modificarclienterfc);
  gtk_table_attach (GTK_TABLE (table14), entry_modificarclienterfc, 5, 8, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_size_request (entry_modificarclienterfc, 80, 25);

  g_signal_connect_swapped ((gpointer) Modificar_cliente, "show",
                            G_CALLBACK (on_Modificar_cliente_show_actualizar),
                            GTK_OBJECT (combo_modificarclientelista));
  g_signal_connect_data ((gpointer) Modificar_cliente, "show",
                         G_CALLBACK (on_Modificar_cliente_show_lista),
                         GTK_OBJECT (clist_modificarcliente),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) Modificar_cliente, "show",
                         G_CALLBACK (gtk_widget_grab_focus),
                         GTK_OBJECT (entry_modificarclientebuscar),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) entry_modificarclientebuscar, "activate",
                            G_CALLBACK (on_entry_modificarclientebuscar_activate),
                            GTK_OBJECT (clist_modificarcliente));
  g_signal_connect_data ((gpointer) entry_modificarclientebuscar, "activate",
                         G_CALLBACK (gtk_widget_grab_focus),
                         GTK_OBJECT (clist_modificarcliente),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) btn_modificarcliente, "clicked",
                            G_CALLBACK (on_btn_modificarcliente_clicked_nombre),
                            GTK_OBJECT (entry_modificarclientenombre));
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_domicilio),
                         GTK_OBJECT (entry_modificarclientedomicilio),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_colonia),
                         GTK_OBJECT (entry_modificarclientecolonia),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_ciudad_estado),
                         GTK_OBJECT (entry_modificarclienteciudad_estado),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_telefono),
                         GTK_OBJECT (entry_modificarclientetelefono),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_telefono2),
                         GTK_OBJECT (entry_modificarclientetelefono2),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_telefono3),
                         GTK_OBJECT (entry_modificarclientetelefono3),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_cp),
                         GTK_OBJECT (entry_modificarclientecp),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_rfc),
                         GTK_OBJECT (entry_modificarclienterfc),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_contacto),
                         GTK_OBJECT (entry_modificarclientecontacto),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_lista),
                         GTK_OBJECT (combo_entry_modificarclientelista),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_pago),
                         GTK_OBJECT (combo_entry_modificarclientepago),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_formato),
                         GTK_OBJECT (combo_entry_modificarclienteformato),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_calles),
                         GTK_OBJECT (entry_modificarclienteentre_calles),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_clicked_vencimiento),
                         GTK_OBJECT (entry_modificarclientevencimiento),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_after ((gpointer) btn_modificarcliente, "clicked",
                          G_CALLBACK (on_btn_modificarcliente_clicked),
                          NULL);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (on_btn_modificarcliente_lista),
                         GTK_OBJECT (clist_modificarcliente),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) btn_modificarcliente, "clicked",
                         G_CALLBACK (gtk_widget_grab_focus),
                         GTK_OBJECT (entry_modificarclientebuscar),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) entry_modificarclientenombre, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclientedomicilio));
  g_signal_connect_swapped ((gpointer) entry_modificarclientedomicilio, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclientecolonia));
  g_signal_connect_swapped ((gpointer) entry_modificarclientecolonia, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclienteciudad_estado));
  g_signal_connect_swapped ((gpointer) entry_modificarclienteciudad_estado, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclientecp));
  g_signal_connect_swapped ((gpointer) entry_modificarclientetelefono2, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclientetelefono3));
  g_signal_connect_swapped ((gpointer) entry_modificarclientetelefono3, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclienterfc));
  g_signal_connect_swapped ((gpointer) entry_modificarclienteentre_calles, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclientecontacto));
  g_signal_connect_swapped ((gpointer) entry_modificarclientecontacto, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (combo_entry_modificarclientelista));
  g_signal_connect_swapped ((gpointer) entry_modificarclientevencimiento, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (btn_modificarcliente));
  g_signal_connect_swapped ((gpointer) entry_modificarclientetelefono, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclientetelefono2));
  g_signal_connect ((gpointer) clist_modificarcliente, "select_row",
                    G_CALLBACK (on_clist_modificarcliente_select_row_codigo),
                    NULL);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_nombre),
                         GTK_OBJECT (entry_modificarclientenombre),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_domicilio),
                         GTK_OBJECT (entry_modificarclientedomicilio),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_colonia),
                         GTK_OBJECT (entry_modificarclientecolonia),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_ciudad_estado),
                         GTK_OBJECT (entry_modificarclienteciudad_estado),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_cp),
                         GTK_OBJECT (entry_modificarclientecp),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_telefono),
                         GTK_OBJECT (entry_modificarclientetelefono),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_telefono2),
                         GTK_OBJECT (entry_modificarclientetelefono2),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_telefono3),
                         GTK_OBJECT (entry_modificarclientetelefono3),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_rfc),
                         GTK_OBJECT (entry_modificarclienterfc),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_entrecalles),
                         GTK_OBJECT (entry_modificarclienteentre_calles),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_contacto),
                         GTK_OBJECT (entry_modificarclientecontacto),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_lista),
                         GTK_OBJECT (combo_entry_modificarclientelista),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_pago),
                         GTK_OBJECT (combo_entry_modificarclientepago),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_formato),
                         GTK_OBJECT (combo_entry_modificarclienteformato),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (on_clist_modificarcliente_select_row_vencimiento),
                         GTK_OBJECT (entry_modificarclientevencimiento),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_data ((gpointer) clist_modificarcliente, "select_row",
                         G_CALLBACK (gtk_widget_grab_focus),
                         GTK_OBJECT (entry_modificarclientenombre),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) btn_modificarclientecancelar, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (Modificar_cliente));
  g_signal_connect_swapped ((gpointer) combo_entry_modificarclientelista, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (combo_entry_modificarclientepago));
  g_signal_connect ((gpointer) combo_entry_modificarclientelista, "changed",
                    G_CALLBACK (on_combo_entry_modificarclientelista_changed),
                    NULL);
  g_signal_connect_swapped ((gpointer) combo_entry_modificarclientepago, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (combo_entry_modificarclienteformato));
  g_signal_connect_swapped ((gpointer) combo_entry_modificarclienteformato, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclientevencimiento));
  g_signal_connect_swapped ((gpointer) entry_modificarclientecp, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclientetelefono));
  g_signal_connect_swapped ((gpointer) entry_modificarclienterfc, "activate",
                            G_CALLBACK (gtk_widget_grab_focus),
                            GTK_OBJECT (entry_modificarclienteentre_calles));

  gtk_label_set_mnemonic_widget (GTK_LABEL (label118), entry_modificarclientebuscar);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label96), entry_modificarclientenombre);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label98), entry_modificarclientecolonia);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label100), entry_modificarclientecp);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label101), entry_modificarclientetelefono);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label104), entry_modificarclienterfc);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label105), entry_modificarclienteentre_calles);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label106), entry_modificarclientecontacto);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label107), combo_entry_modificarclientelista);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label125), combo_entry_modificarclientepago);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label126), combo_entry_modificarclienteformato);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label159), entry_modificarclientevencimiento);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label97), entry_modificarclientedomicilio);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label99), entry_modificarclienteciudad_estado);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modificar_cliente, Modificar_cliente, "Modificar_cliente");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, table14, "table14");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label118, "label118");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientebuscar, "entry_modificarclientebuscar");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, btn_modificarcliente, "btn_modificarcliente");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, image52, "image52");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label96, "label96");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label98, "label98");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label100, "label100");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label101, "label101");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label102, "label102");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label103, "label103");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label104, "label104");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label105, "label105");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label106, "label106");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label107, "label107");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label125, "label125");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label126, "label126");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label159, "label159");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientenombre, "entry_modificarclientenombre");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientedomicilio, "entry_modificarclientedomicilio");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientecolonia, "entry_modificarclientecolonia");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclienteciudad_estado, "entry_modificarclienteciudad_estado");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientetelefono2, "entry_modificarclientetelefono2");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientetelefono3, "entry_modificarclientetelefono3");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclienteentre_calles, "entry_modificarclienteentre_calles");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientecontacto, "entry_modificarclientecontacto");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientevencimiento, "entry_modificarclientevencimiento");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientetelefono, "entry_modificarclientetelefono");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label97, "label97");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, scrolledwindow9, "scrolledwindow9");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, clist_modificarcliente, "clist_modificarcliente");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label93, "label93");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label94, "label94");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label95, "label95");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, label99, "label99");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, image50, "image50");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, btn_modificarclientecancelar, "btn_modificarclientecancelar");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, image53, "image53");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, combo_modificarclientelista, "combo_modificarclientelista");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, combo_entry_modificarclientelista, "combo_entry_modificarclientelista");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, combo_modificarclientepago, "combo_modificarclientepago");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, combo_entry_modificarclientepago, "combo_entry_modificarclientepago");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, combo_modificarclienteformato, "combo_modificarclienteformato");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, combo_entry_modificarclienteformato, "combo_entry_modificarclienteformato");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclientecp, "entry_modificarclientecp");
  GLADE_HOOKUP_OBJECT (Modificar_cliente, entry_modificarclienterfc, "entry_modificarclienterfc");

  gtk_widget_grab_focus (entry_modificarclientebuscar);
  gtk_window_add_accel_group (GTK_WINDOW (Modificar_cliente), accel_group);

  return Modificar_cliente;
}

