/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

/*#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)*/

GtkWidget*
create_win_facturacion_no_facturado (void)
{
  GtkWidget *win_facturacion_no_facturado;
  GtkWidget *fixed1;
  GtkWidget *entry_folio_win_no_facturado;
  GtkWidget *button4;
  GtkWidget *hseparator1;
  GtkWidget *entry_factura_win_no_facturado;
  GtkWidget *scrolledwindow_obs_win_no_facturado;
  GtkWidget *txtv_obs_win_no_facturado;
  GtkWidget *label14;
  GtkWidget *entry_cliente_win_no_facturado;
  GtkWidget *label9;
  GtkWidget *label_tot_articulos_win_no_facturado;
  GtkWidget *label1;
  GtkWidget *entry_limite_articulos_win_no_facturado;
  GtkWidget *label19;
  GtkWidget *vseparator1;
  GtkWidget *btn_quitar_win_no_facturado;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label16;
  GtkWidget *btn_aceptar_win_no_facturado;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label12;
  GtkWidget *btn_cancelar_win_no_facturado;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label13;
  GtkWidget *label17;
  GtkWidget *scrolledwindow_win_no_facturado;
  GtkWidget *clist_folios_win_no_facturado;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label_id_cliente;
  GtkWidget *btn_agregar_win_no_facturado;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label10;
  GtkWidget *label15;
  GtkWidget *btn_buscar_folio_win_no_facturado;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11;
  GtkWidget *btn_buscar_cliente_win_no_facturado;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label18;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  win_facturacion_no_facturado = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (win_facturacion_no_facturado, 750, 418);
  gtk_window_set_title (GTK_WINDOW (win_facturacion_no_facturado), _("Facturacion de folios no facturados"));
  gtk_window_set_position (GTK_WINDOW (win_facturacion_no_facturado), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (win_facturacion_no_facturado), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (win_facturacion_no_facturado), fixed1);

  entry_folio_win_no_facturado = gtk_entry_new ();
  gtk_widget_show (entry_folio_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_folio_win_no_facturado, 8, 40);
  gtk_widget_set_size_request (entry_folio_win_no_facturado, 272, 24);

  button4 = gtk_button_new_with_mnemonic (_("Agregar"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1), button4, -1073754136, 0);
  gtk_widget_set_size_request (button4, 88, 24);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator1, 8, 360);
  gtk_widget_set_size_request (hseparator1, 736, 16);

  entry_factura_win_no_facturado = gtk_entry_new ();
  gtk_widget_show (entry_factura_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_factura_win_no_facturado, 584, 80);
  gtk_widget_set_size_request (entry_factura_win_no_facturado, 144, 24);

  scrolledwindow_obs_win_no_facturado = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_obs_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow_obs_win_no_facturado, 528, 152);
  gtk_widget_set_size_request (scrolledwindow_obs_win_no_facturado, 208, 168);

  txtv_obs_win_no_facturado = gtk_text_view_new ();
  gtk_widget_show (txtv_obs_win_no_facturado);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_obs_win_no_facturado), txtv_obs_win_no_facturado);

  label14 = gtk_label_new (_("Observaciones de la facturacion :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed1), label14, 528, 128);
  gtk_widget_set_size_request (label14, 200, 16);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label14), TRUE);

  entry_cliente_win_no_facturado = gtk_entry_new ();
  gtk_widget_show (entry_cliente_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_cliente_win_no_facturado, 584, 32);
  gtk_widget_set_size_request (entry_cliente_win_no_facturado, 64, 24);

  label9 = gtk_label_new (_("<b>Total de articulos diferentes:</b>"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 240, 328);
  gtk_widget_set_size_request (label9, 184, 24);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);
  gtk_label_set_justify (GTK_LABEL (label9), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label9), TRUE);

  label_tot_articulos_win_no_facturado = gtk_label_new (_("<span color=\"#0000FF\">0</span>"));
  gtk_widget_show (label_tot_articulos_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), label_tot_articulos_win_no_facturado, 424, 328);
  gtk_widget_set_size_request (label_tot_articulos_win_no_facturado, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (label_tot_articulos_win_no_facturado), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_tot_articulos_win_no_facturado), GTK_JUSTIFY_RIGHT);
  gtk_label_set_line_wrap (GTK_LABEL (label_tot_articulos_win_no_facturado), TRUE);

  label1 = gtk_label_new (_("Por favor escriba los folios que desea facturar:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 8, 8);
  gtk_widget_set_size_request (label1, 280, 24);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);

  entry_limite_articulos_win_no_facturado = gtk_entry_new ();
  gtk_widget_show (entry_limite_articulos_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_limite_articulos_win_no_facturado, 424, 8);
  gtk_widget_set_size_request (entry_limite_articulos_win_no_facturado, 48, 24);
  gtk_entry_set_text (GTK_ENTRY (entry_limite_articulos_win_no_facturado), _("10"));

  label19 = gtk_label_new (_("Articulos por factura:"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed1), label19, 296, 8);
  gtk_widget_set_size_request (label19, 128, 24);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label19), TRUE);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed1), vseparator1, 504, 8);
  gtk_widget_set_size_request (vseparator1, 16, 352);

  btn_quitar_win_no_facturado = gtk_button_new ();
  gtk_widget_show (btn_quitar_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_quitar_win_no_facturado, 8, 328);
  gtk_widget_set_size_request (btn_quitar_win_no_facturado, 67, 24);
  gtk_widget_set_sensitive (btn_quitar_win_no_facturado, FALSE);
  gtk_widget_add_accelerator (btn_quitar_win_no_facturado, "clicked", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (btn_quitar_win_no_facturado), GTK_RELIEF_NONE);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (btn_quitar_win_no_facturado), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = create_pixmap (win_facturacion_no_facturado, "quitar.png");
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Quitar"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox5), label16, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);

  btn_aceptar_win_no_facturado = gtk_button_new ();
  gtk_widget_show (btn_aceptar_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_aceptar_win_no_facturado, 296, 376);
  gtk_widget_set_size_request (btn_aceptar_win_no_facturado, 105, 32);
  gtk_widget_add_accelerator (btn_aceptar_win_no_facturado, "clicked", accel_group,
                              GDK_F1, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (btn_aceptar_win_no_facturado), GTK_RELIEF_NONE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (btn_aceptar_win_no_facturado), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = create_pixmap (win_facturacion_no_facturado, "carnesbecerra_aceptar.jpg");
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Aceptar"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);

  btn_cancelar_win_no_facturado = gtk_button_new ();
  gtk_widget_show (btn_cancelar_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_cancelar_win_no_facturado, 408, 376);
  gtk_widget_set_size_request (btn_cancelar_win_no_facturado, 105, 32);
  gtk_widget_add_accelerator (btn_cancelar_win_no_facturado, "clicked", accel_group,
                              GDK_Escape, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (btn_cancelar_win_no_facturado), GTK_RELIEF_NONE);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (btn_cancelar_win_no_facturado), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = create_pixmap (win_facturacion_no_facturado, "carnesbecerra_cancelar.jpg");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Cancelar"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox4), label13, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_LEFT);

  label17 = gtk_label_new (_("Cliente :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed1), label17, 528, 32);
  gtk_widget_set_size_request (label17, 56, 24);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label17), TRUE);

  scrolledwindow_win_no_facturado = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow_win_no_facturado, 8, 80);
  gtk_widget_set_size_request (scrolledwindow_win_no_facturado, 496, 240);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow_win_no_facturado), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  clist_folios_win_no_facturado = gtk_clist_new (6);
  gtk_widget_show (clist_folios_win_no_facturado);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_win_no_facturado), clist_folios_win_no_facturado);
  gtk_clist_set_column_width (GTK_CLIST (clist_folios_win_no_facturado), 0, 56);
  gtk_clist_set_column_width (GTK_CLIST (clist_folios_win_no_facturado), 1, 74);
  gtk_clist_set_column_width (GTK_CLIST (clist_folios_win_no_facturado), 2, 234);
  gtk_clist_set_column_width (GTK_CLIST (clist_folios_win_no_facturado), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_folios_win_no_facturado), 4, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist_folios_win_no_facturado), 5, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist_folios_win_no_facturado));

  label4 = gtk_label_new (_("No. Folio"));
  gtk_widget_show (label4);
  gtk_clist_set_column_widget (GTK_CLIST (clist_folios_win_no_facturado), 0, label4);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  label5 = gtk_label_new (_("Fecha Venta"));
  gtk_widget_show (label5);
  gtk_clist_set_column_widget (GTK_CLIST (clist_folios_win_no_facturado), 1, label5);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  label6 = gtk_label_new (_("Articulo"));
  gtk_widget_show (label6);
  gtk_clist_set_column_widget (GTK_CLIST (clist_folios_win_no_facturado), 2, label6);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);

  label7 = gtk_label_new (_("Total"));
  gtk_widget_show (label7);
  gtk_clist_set_column_widget (GTK_CLIST (clist_folios_win_no_facturado), 3, label7);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);

  label8 = gtk_label_new (_("ID_articulo"));
  gtk_widget_show (label8);
  gtk_clist_set_column_widget (GTK_CLIST (clist_folios_win_no_facturado), 4, label8);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);

  label_id_cliente = gtk_label_new (_("ID_cliente"));
  gtk_widget_show (label_id_cliente);
  gtk_clist_set_column_widget (GTK_CLIST (clist_folios_win_no_facturado), 5, label_id_cliente);
  gtk_label_set_justify (GTK_LABEL (label_id_cliente), GTK_JUSTIFY_LEFT);

  btn_agregar_win_no_facturado = gtk_button_new ();
  gtk_widget_show (btn_agregar_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_agregar_win_no_facturado, 296, 40);
  gtk_widget_set_size_request (btn_agregar_win_no_facturado, 80, 32);
  gtk_widget_add_accelerator (btn_agregar_win_no_facturado, "clicked", accel_group,
                              GDK_A, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (btn_agregar_win_no_facturado), GTK_RELIEF_NONE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (btn_agregar_win_no_facturado), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = create_pixmap (win_facturacion_no_facturado, "agregar.png");
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Agregar"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox1), label10, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);

  label15 = gtk_label_new (_("Factura:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed1), label15, 528, 80);
  gtk_widget_set_size_request (label15, 56, 24);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label15), TRUE);

  btn_buscar_folio_win_no_facturado = gtk_button_new ();
  gtk_widget_show (btn_buscar_folio_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_buscar_folio_win_no_facturado, 384, 40);
  gtk_widget_set_size_request (btn_buscar_folio_win_no_facturado, 80, 32);
  gtk_widget_add_accelerator (btn_buscar_folio_win_no_facturado, "clicked", accel_group,
                              GDK_B, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (btn_buscar_folio_win_no_facturado), GTK_RELIEF_NONE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (btn_buscar_folio_win_no_facturado), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = create_pixmap (win_facturacion_no_facturado, "buscar.png");
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Buscar..."));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_LEFT);

  btn_buscar_cliente_win_no_facturado = gtk_button_new ();
  gtk_widget_show (btn_buscar_cliente_win_no_facturado);
  gtk_fixed_put (GTK_FIXED (fixed1), btn_buscar_cliente_win_no_facturado, 656, 28);
  gtk_widget_set_size_request (btn_buscar_cliente_win_no_facturado, 80, 30);
  gtk_widget_add_accelerator (btn_buscar_cliente_win_no_facturado, "clicked", accel_group,
                              GDK_F9, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (btn_buscar_cliente_win_no_facturado), GTK_RELIEF_NONE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btn_buscar_cliente_win_no_facturado), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = create_pixmap (win_facturacion_no_facturado, "buscar.png");
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("buscar"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox6), label18, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) win_facturacion_no_facturado, "show",
                    G_CALLBACK (on_win_facturacion_no_facturado_show),
                    NULL);
  g_signal_connect ((gpointer) entry_folio_win_no_facturado, "changed",
                    G_CALLBACK (on_entry_folio_win_no_facturado_changed),
                    NULL);
  g_signal_connect ((gpointer) entry_factura_win_no_facturado, "changed",
                    G_CALLBACK (on_entry_factura_win_no_facturado_changed),
                    NULL);
  g_signal_connect ((gpointer) entry_cliente_win_no_facturado, "changed",
                    G_CALLBACK (on_entry_cliente_win_no_facturado_changed),
                    NULL);
  g_signal_connect ((gpointer) entry_limite_articulos_win_no_facturado, "changed",
                    G_CALLBACK (on_entry_limite_articulos_win_no_facturado_changed),
                    NULL);
  g_signal_connect ((gpointer) btn_quitar_win_no_facturado, "clicked",
                    G_CALLBACK (on_btn_quitar_win_no_facturado_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_aceptar_win_no_facturado, "clicked",
                    G_CALLBACK (on_btn_aceptar_win_no_facturado_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_agregar_win_no_facturado, "clicked",
                    G_CALLBACK (on_btn_agregar_win_no_facturado_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_buscar_folio_win_no_facturado, "clicked",
                    G_CALLBACK (on_btn_buscar_folio_win_no_facturado_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_buscar_cliente_win_no_facturado, "clicked",
                    G_CALLBACK (on_btn_buscar_cliente_win_no_facturado_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (win_facturacion_no_facturado, win_facturacion_no_facturado, "win_facturacion_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, entry_folio_win_no_facturado, "entry_folio_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, button4, "button4");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, entry_factura_win_no_facturado, "entry_factura_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, scrolledwindow_obs_win_no_facturado, "scrolledwindow_obs_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, txtv_obs_win_no_facturado, "txtv_obs_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label14, "label14");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, entry_cliente_win_no_facturado, "entry_cliente_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label9, "label9");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label_tot_articulos_win_no_facturado, "label_tot_articulos_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label1, "label1");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, entry_limite_articulos_win_no_facturado, "entry_limite_articulos_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label19, "label19");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, btn_quitar_win_no_facturado, "btn_quitar_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, image5, "image5");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label16, "label16");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, btn_aceptar_win_no_facturado, "btn_aceptar_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, image3, "image3");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label12, "label12");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, btn_cancelar_win_no_facturado, "btn_cancelar_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, image4, "image4");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label13, "label13");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label17, "label17");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, scrolledwindow_win_no_facturado, "scrolledwindow_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, clist_folios_win_no_facturado, "clist_folios_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label4, "label4");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label5, "label5");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label6, "label6");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label7, "label7");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label8, "label8");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label_id_cliente, "label_id_cliente");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, btn_agregar_win_no_facturado, "btn_agregar_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, image1, "image1");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label10, "label10");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label15, "label15");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, btn_buscar_folio_win_no_facturado, "btn_buscar_folio_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, image2, "image2");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label11, "label11");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, btn_buscar_cliente_win_no_facturado, "btn_buscar_cliente_win_no_facturado");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, image6, "image6");
  GLADE_HOOKUP_OBJECT (win_facturacion_no_facturado, label18, "label18");

  gtk_window_add_accel_group (GTK_WINDOW (win_facturacion_no_facturado), accel_group);

  return win_facturacion_no_facturado;
}

