/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_caja (void);
GtkWidget* create_Alta_clientes_caja (void);
GtkWidget* create_Datos_cliente (void);
GtkWidget* create_Seguridad (void);
GtkWidget* create_Alta_empleado (void);
GtkWidget* create_Inicio_Sesion (void);
GtkWidget* create_Configuracion_BD (void);
GtkWidget* create_Articulos (void);
GtkWidget* create_dialog_Articulo_Eder (void);
GtkWidget* create_Cancela_Venta_Eder (void);
GtkWidget* create_dialog_Cacela_Venta (void);
GtkWidget* create_Retiro_Efectivo (void);
GtkWidget* create_Confirmar_venta (void);
GtkWidget* create_Facturar (void);
GtkWidget* create_Reimprimir_ticket (void);
GtkWidget* create_dialog_facturar (void);
GtkWidget* create_Corte_global (void);
GtkWidget* create_Acerca_de (void);
GtkWidget* create_V_pedidos (void);
GtkWidget* create_V_observaciones (void);
GtkWidget* create_Cierre_facturas (void);
GtkWidget* create_Buscar_venta (void);
GtkWidget* create_Buscar_articulo (void);
GtkWidget* create_Buscar_cliente (void);
GtkWidget* create_Reimprimir_pedido (void);
GtkWidget* create_Domicilio_envio (void);
GtkWidget* create_Descuento (void);
GtkWidget* create_win_bascula (void);
GtkWidget* create_win_trabajando (void);
GtkWidget* create_win_cajon_abierto (void);
GtkWidget* create_Modificar_cliente (void);
